export default function () {
  return {
    players: [
      {
        name: 'Ognjen Jaramaz',
        img: 'ognjen_jaramaz.svg',
        number: '#10',
        height: '1.98',
        position: 'SG',
        SG: '1.98m',
        PPG: '168',
        RPG: '134',
        APG: '80',
        BPG: '14',
        SPG: '14',
        FPG: '168',
        TPM: '34',
        TPP: '80',
        FPPG: '14',
      },
      {
        name: 'Marcus Paige',
        img: 'marcus_paige.svg',
        number: '#5',
        height: '1.98',
        position: 'SG',
        SG: '1.98m',
        PPG: '168',
        RPG: '134',
        APG: '80',
        BPG: '14',
        SPG: '14',
        FPG: '168',
        TPM: '34',
        TPP: '80',
        FPPG: '14',
      },
      {
        name: 'Rage Zagorac',
        img: 'rade_zagorac.svg',
        number: '#3',
        height: '1.98',
        position: 'SG',
        SG: '1.98m',
        PPG: '168',
        RPG: '134',
        APG: '80',
        BPG: '14',
        SPG: '14',
        FPG: '168',
        TPM: '34',
        TPP: '80',
        FPPG: '14',
      },
      {
        name: 'William Mosley',
        img: 'william_mosley.svg',
        number: '#42',
        height: '1.98',
        position: 'SG',
        PPG: '168',
        RPG: '134',
        APG: '80',
        BPG: '14',
        SPG: '14',
        FPG: '168',
        TPM: '34',
        TPP: '80',
        FPPG: '14',
      },
      {
        name: 'Rasawn Thomas',
        img: 'rasawn_thomas.svg',
        number: '#42',
        height: '1.98',
        position: 'SG',
        PPG: '168',
        RPG: '134',
        APG: '80',
        BPG: '14',
        SPG: '14',
        FPG: '168',
        TPM: '34',
        TPP: '80',
        FPPG: '14',
      },
      {
        name: 'Novica Velickovic',
        img: 'novica_velickovic.svg',
        number: '#12',
        height: '1.98',
        position: 'SG',
        PPG: '168',
        RPG: '134',
        APG: '80',
        BPG: '14',
        SPG: '14',
        FPG: '168',
        TPM: '34',
        TPP: '80',
        FPPG: '14',
      },
      {
        name: 'Novica Velickovic',
        img: 'novica_velickovic.svg',
        number: '#12',
        height: '1.98',
        position: 'SG',
        PPG: '168',
        RPG: '134',
        APG: '80',
        BPG: '14',
        SPG: '14',
        FPG: '168',
        TPM: '34',
        TPP: '80',
        FPPG: '14',
      },
      {
        name: 'Novica Velickovic',
        img: 'novica_velickovic.svg',
        number: '#12',
        height: '1.98',
        position: 'SG',
        PPG: '168',
        RPG: '134',
        APG: '80',
        BPG: '14',
        SPG: '14',
        FPG: '168',
        TPM: '34',
        TPP: '80',
        FPPG: '14',
      },
      {
        name: 'Novica Velickovic',
        img: 'novica_velickovic.svg',
        number: '#12',
        height: '1.98',
        position: 'SG',
        PPG: '168',
        RPG: '134',
        APG: '80',
        BPG: '14',
        SPG: '14',
        FPG: '168',
        TPM: '34',
        TPP: '80',
        FPPG: '14',
      },
      {
        name: 'Novica Velickovic',
        img: 'novica_velickovic.svg',
        number: '#12',
        height: '1.98',
        position: 'SG',
        PPG: '168',
        RPG: '134',
        APG: '80',
        BPG: '14',
        SPG: '14',
        FPG: '168',
        TPM: '34',
        TPP: '80',
        FPPG: '14',
      },
      {
        name: 'Novica Velickovic',
        img: 'novica_velickovic.svg',
        number: '#12',
        height: '1.98',
        position: 'SG',
        PPG: '168',
        RPG: '134',
        APG: '80',
        BPG: '14',
        SPG: '14',
        FPG: '168',
        TPM: '34',
        TPP: '80',
        FPPG: '14',
      },
      {
        name: 'Novica Velickovic',
        img: 'novica_velickovic.svg',
        number: '#12',
        height: '1.98',
        position: 'SG',
        PPG: '168',
        RPG: '134',
        APG: '80',
        BPG: '14',
        SPG: '14',
        FPG: '168',
        TPM: '34',
        TPP: '80',
        FPPG: '14',
      }
    ],
    staff: [
      {
        name: 'Andrea Trinchieri',
        position: 'Head Coach',
        img: 'trainer.png'
      },
      {
        name: 'Coach Coach',
        position: 'Assistant',
        img: ''
      },
      {
        name: 'Coach Coach',
        position: 'Assistant',
        img: ''
      },
      {
        name: 'Coach Coach',
        position: 'Assistant',
        img: ''
      }
    ]
  }
}
